version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: sk_website_postgres
    env_file:
      - ./.env
    ports:
      - 5433:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume: